name: Update Weekly Time Spent

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt || true  # If you need dependencies

      - name: Run Update Script
        run: python update_readme.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update weekly time spent section" || echo "No changes to commit"
          git push
